server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanihuangdi/springCloud1.git
          searchPaths: config
          username: hanihuangdi
          password: cfdwechat123
      label: master
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/