server:
  port: 8766
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
  cloud:
    config:
       server:
         native:
            search-location: classpath:/shared